Loading pytorch-gpu/py3/2.2.0
  Loading requirement: cuda/12.2.0 nccl/2.19.3-1-cuda cudnn/8.9.5.30-cuda
    gcc/10.1.0 openmpi/4.1.5-cuda intel-mkl/2020.4 magma/2.7.2-cuda sox/14.4.2
    sparsehash/2.0.3 libjpeg-turbo/2.1.3
+ export NCCL_DEBUG=INFO
+ NCCL_DEBUG=INFO
+ export PYTHONFAULTHANDLER=1
+ PYTHONFAULTHANDLER=1
+ export TORCH_USE_CUDA_DSA=1
+ TORCH_USE_CUDA_DSA=1
+ export CUBLAS_WORKSPACE_CONFIG=:16:8
+ CUBLAS_WORKSPACE_CONFIG=:16:8
+ srun python CRBD/GNN_avg.py
Traceback (most recent call last):
  File "/lustre/fswork/projects/rech/hvr/uhd88jk/Phylo_Inference/CRBD/GNN_avg.py", line 272, in <module>
    np.save("/home/amelie/These/Phylo_Inference/CRBD/results/pred_crbd_GNN_avg.npy", pred_array)
  File "<__array_function__ internals>", line 200, in save
  File "/gpfslocalsup/pub/anaconda-py3/2023.09/envs/pytorch-gpu-2.2.0+py3.11.7/lib/python3.11/site-packages/numpy/lib/npyio.py", line 518, in save
    file_ctx = open(file, "wb")
               ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/amelie/These/Phylo_Inference/CRBD/results/pred_crbd_GNN_avg.npy'
srun: error: jean-zay-iam05: task 0: Exited with exit code 1
srun: Terminating StepId=2058827.0
